### ISSUE TITLE
zip data already has an archive comment

### ISSUE THREAD

**Issue by Fusseldieb** [HemanthJabalpuri/signapk#1]
```
java.lang.IllegalArgumentException: zip data already has an archive comment
        at com.android.signapk.SignApk.main(SignApk.java:121)
```

While resigning a "invalid" signature zip

**Comment by HemanthJabalpuri** [comment]
> ```
> java.lang.IllegalArgumentException: zip data already has an archive comment
>         at com.android.signapk.SignApk.main(SignApk.java:121)
> ```
> 
> While resigning a "invalid" signature zip

zip the contents again with other archiver

**Comment by Fusseldieb** [comment]
![image](https://github.com/HemanthJabalpuri/signapk/assets/4715129/9438ece3-8e5d-4fcc-8bb5-7672643bc981)

Deleting the contents of the zip file apparently did the job. Now it signed it.

> zip the contents again with other archiver

That's a blazing fast response. Thank you.

**Comment by HemanthJabalpuri** [comment]
By the way, for what purpose you need to sign the zip?

**Comment by Fusseldieb** [comment]
> By the way, for what purpose you need to sign the zip?

I need to sideload this firmware.zip in a stock Android recovery. I patched it with a custom boot.img inside. I don't know if it will work, but at this point I'm out of any other options :)

EDIT: Yep! That worked!

**Comment by HemanthJabalpuri** [comment]
May I know which Android smartphone it is? (Just curious how OEMs use test keys for their OTA)

**Comment by Fusseldieb** [comment]
> May I know which Android smartphone it is? (Just curious how OEMs use test keys for their OTA)

Just a shitty Noname "HOW" tablet. Specifically a HT-705 XS.

It did flash the package. /system errored with status 7, but continued and flashed /vendor, boot, env with sucess.

Still, the tablet didn't boot up with the custom boot.img. Still figuring out why.

Anyways, it worked :)

EDIT: Figured it out. Forgot to `fastboot oem unlock`
